apiVersion: v1
kind: Service
metadata:
  name: tagging-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: tagging-service
  ports:
    - port: {{ .Values.tagging.port }}
      targetPort: {{ .Values.tagging.port }}