apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tagging-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: tagging.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tagging-service
                port:
                  number: {{ .Values.tagging.port }}