apiVersion: v1
kind: Service
metadata:
  name: versioning-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: versioning-service
ports:
  - name: http
    port: {{ .Values.versioning.port }}
    targetPort: {{ .Values.versioning.port }}