 global:
  scrape_interval: 15s

 scrape_configs:
  - job_name: "versioning-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["versioning-service:3000"]

  - job_name: "tagging-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["tagging-service:3000"]
      