apiVersion: v1
kind: ConfigMap
metadata:
  name: tagging-config
  namespace: cse474-prod
data:
  NODE_ENV: "production"
  PORT: "3000"
  SERVICE_NAME: "tagging-service"
  DB_HOST: "tagging-db"
  DB_PORT: "5432"
  DB_NAME: "tagging_db"

  SERVICE_NAME: "tagging-service"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger.default.svc.cluster.local:4318/v1/traces"