apiVersion: v1
kind: Service
metadata:
  name: tagging-service
  namespace: cse474-prod
spec:
  type: ClusterIP
  selector:
    app: tagging-service
ports:
  - name: http
    port: 3000
    targetPort: 3000