apiVersion: v1
kind: ConfigMap
metadata:
  name: versioning-config
  namespace: cse474-prod
data:
  NODE_ENV: "production"
  PORT: "3000"
  SERVICE_NAME: "versioning-service"
  DB_HOST: "versioning-db"
  DB_PORT: "5432"
  DB_NAME: "versioning_db"
  KAFKA_BROKERS: "kafka:9092"